name: Build and Publish
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4


      - name: Configura jdk
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          architecture: x64
          cache: maven

      - name: Executar os testes com Maven
        working-directory: ./application
        run: mvn test


      - name: Empacotar artifact com Maven
        working-directory: ./application
        run: mvn package -DskipTests


      - name: Upload do artifact
        uses: actions/upload-artifact@v4
        with:
          name: gamelist-api-artifact
          path: ./application/target

  publish_to_registry:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: gamelist-api-artifact

      - name: Login em Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Extrai metadata (tags, labels) do Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/gamelistapi

      - name: Constroi e envia imagem Docker
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./application/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


      - name: Gera atestado da imagem
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: index.docker.io/${{ secrets.DOCKER_USERNAME }}/gamelistapi
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true








